# Generated by Django 3.2 on 2021-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=254)),
                ('middleName', models.CharField(max_length=254)),
                ('lastName', models.CharField(max_length=254)),
                ('specialization', models.CharField(max_length=254)),
                ('prcLicenseNumber', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=254)),
                ('middleName', models.CharField(max_length=254)),
                ('lastName', models.CharField(max_length=254)),
                ('birthDate', models.DateField()),
                ('sex', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
